name: Build Server
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - name: linux-x64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build_name: polli-live
          - name: win-x64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            build_name: polli-live.exe
          - name: macos-x64
            runner: macos-latest
            target: x86_64-apple-darwin
            build_name: polli-live
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
            build_name: polli-live

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Binary
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}
        working-directory: ./server
